### ISSUE TITLE
Nodejs support for uppy server

### ISSUE THREAD

**Issue by jazkh** [transloadit/uppy-server#86] opened 2018-04-27 05:40 UTC
Hello,
I was wondering if uppy server has any documentation for nodejs server to handle file uploading?
Any example on how to pass file metadata/information from uppy (front end) to nodejs backend and then use those information to save in database?
Thank you

**Comment by damianijr** [comment] 2018-04-27 13:42
@jazkh you can define  your upload URL in front-end, then uppy-server at end will dispatch the file to these URL with all information defined.. and then you could save all of then in database.

Front-end:
` const uppy = new Uppy()
      .use(XHRUpload, {
        endpoint: 'http://your-upload-url',
        headers: {
          Authorization: `Bearer ${token}`,
        },
        formData: true,
        fieldName: 'itemFile',
      })
      .run();`

and you could use [multer](https://github.com/expressjs/multer), [express-fileupload](https://www.npmjs.com/package/express-fileupload) or something like that to handle multipart request and save file and metadata in database.

**Comment by jazkh** [comment] 2018-04-28 02:42
@damianijr I am using Tus node server as backend and uppy client for frontend. 
I am facing GET 404 (Not Found) error when requesting file from backend.

**Comment by Acconut** [comment] 2018-04-29 20:50
> I am using Tus node server as backend and uppy client for frontend.
I am facing GET 404 (Not Found) error when requesting file from backend.

This is how tus-node-server works by design, as you discovered in https://github.com/tus/tus-node-server/issues/84#issuecomment-354624753

**Comment by ifedapoolarewaju** [comment] 2018-05-02 10:15
closing this as the issue is more related with [tus-node-server](https://github.com/tus/tus-node-server/issues/84)

**Closed as completed by ifedapoolarewaju** 2018-05-02 10:15 UTC
