### ISSUE TITLE
404 HTTP error for Dropbox file operations

### ISSUE THREAD

**Issue by vgiotsas** [transloadit/uppy-server#80] opened 2018-04-04 01:52 UTC
After authenticating with Dropbox, only the `list` operation of the root folder works. When I try to list Dropbox sub-folders or get files, the standalone uppy-server returns 404 error because it appends an extra `/` before the file or folder name, e.g.

```
/dropbox/get//filename.ext was not found on this server.
```
When I manually remove the additional `/` and paste the link directly to the browser I get the following message:

```
"No endpoint, file written to uppy server local storage"
```

In the uppy-server output I see the following error message:

```
uppy: 2018-04-04T01:51:00.891Z [error] provider.dropbox.size.error Error in call to API function "files/get_metadata": request body: path: 'filename.ext' did not match pattern '(/(.|[\r\n])*|id:.*)|(rev:[0-9a-f]{9,})|(ns:[0-9]+(/.*)?)'
```

**Comment by ifedapoolarewaju** [comment] 2018-04-04 23:15
> When I try to list Dropbox sub-folders or get files, the standalone uppy-server returns 404 error because it appends an extra / before the file or folder name

are there particular steps that I should follow to reproduce this? I am asking because it seems to work fine for me on the example page here https://uppy.io/examples/dashboard/ Are you also noticing the same error on the example page?

**Comment by ifedapoolarewaju** [comment] 2018-05-02 10:34
closing this as I cannot reproduce

**Closed as completed by ifedapoolarewaju** 2018-05-02 10:34 UTC
